#!/command/with-contenv sh
# shellcheck shell=bash

cd /app/apps/web;
if [ "${USE_JEMALLOC:-false}" = "true" ]; then
    export LD_PRELOAD=/usr/local/lib/libjemalloc.so
fi

# Explicitly set HOSTNAME to override s6-overlay default HOSTNAME environment variable.
export HOSTNAME="${WEB_HOST:-0.0.0.0}"

exec node server.js;
