# =============================================================================
# AI Rules Configuration (Generated by VSCode Extension)
# =============================================================================

# AI Assistant Configuration
AI_ASSISTANT=augment
AI_RULES=.rules/UNIFIED_MEMORY.md .rules/GLOBAL_RULE.md .rules/CODING_STYLE.md .rules/CODE_ANALYSIS.md

# Workflow Configuration
AI_WORKFLOWS=ai-rules,ai-rules-first-run
AI_WORKFLOWS_SOURCE_REPO=carsaig/llm-context

# 1Password Configuration (Documentation - workflows use these as defaults)
# Only GitHub Secret required: OP_SERVICE_ACCOUNT_TOKEN
# These values are built into workflows - no GitHub Variables needed
AI_WORKFLOWS_SECRETS_VAULT=SECRETS
AI_WORKFLOWS_GITHUB_PAT_PATH=Github/PAT_Claude

# Git Configuration
AI_WORKFLOWS_GIT_EMAIL=action@github.com
AI_WORKFLOWS_GIT_NAME=GitHub Action

# =============================================================================
# Setup Instructions:
# 1. Customize AI_ASSISTANT if needed (augment, cursor, zed, windsurf, gemini, claude)
# 2. Update AI_RULES with your specific rule files
# 3. Configure 1Password vault and GitHub PAT path
# 4. Set up GitHub repository secrets and variables
# 5. Commit and push to trigger first-run bootstrap
# =============================================================================
