packages:
  - "packages/*"
  - "apps/*"
  - "tooling/*"
  - "tools/*"
  - "docs"

nodeLinker: hoisted

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  better-sqlite3: true
  core-js: false
  core-js-pure: false
  esbuild: true
  postman-code-generators: false
  protobufjs: true
  re2: true
  sharp: true
  tesseract.js: true

patchedDependencies:
  xcode@3.0.1: "patches/xcode@3.0.1.patch"
  playwright-extra@4.3.6: "patches/playwright-extra@4.3.6.patch"
