// This file is auto-generated by scripts/build-webview-js.ts
// Do not edit manually. Run: pnpm --filter @karakeep/shared generate:webview-js
// Sources: reading-progress-webview-src.ts, reading-progress-core.ts

/**
 * WebView-compatible JavaScript for reading progress tracking.
 * Designed for React Native WebView injection.
 * Uses window-level scrolling only (no container scrolling detection).
 *
 * Exposes these functions on the __readingProgress global:
 * - normalizeText(text)
 * - normalizeTextLength(text)
 * - extractAnchorText(element)
 * - findParagraphByAnchor(container, anchor)
 * - getReadingPosition(container)
 * - scrollToReadingPosition(container, offset, behavior, anchor)
 */
export const READING_PROGRESS_WEBVIEW_JS =
  '"use strict";var __readingProgress=(()=>{var h=Object.defineProperty;var P=Object.getOwnPropertyDescriptor;var b=Object.getOwnPropertyNames;var k=Object.prototype.hasOwnProperty;var C=(e,t)=>{for(var l in t)h(e,l,{get:t[l],enumerable:!0})},N=(e,t,l,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let i of b(t))!k.call(e,i)&&i!==l&&h(e,i,{get:()=>t[i],enumerable:!(n=P(t,i))||n.enumerable});return e};var H=e=>N(h({},"__esModule",{value:!0}),e);var w={};C(w,{getReadingPosition:()=>L,scrollToReadingPosition:()=>E});var d=["p","h1","h2","h3","h4","h5","h6","li","blockquote"],x=d.join(", "),m=50;function f(e){return e.replace(/[\\n\\r\\t]+/g," ").replace(/\\s+/g," ").trim()}function R(e){return f(e).length}function T(e,t){var u,g;let l=Array.from(e.querySelectorAll(x));if(l.length===0)return null;let n=null;for(let a of l){let r=a.getBoundingClientRect();if(r.top>=t){n=a;break}if(r.top<t&&r.bottom>t){n=a;break}}if(!n)return null;let i=f((u=n.textContent)!=null?u:"").slice(0,m),p=document.createTreeWalker(e,NodeFilter.SHOW_TEXT,null),s=0,c;for(;c=p.nextNode();){if(n.contains(c))return{offset:s,anchor:i};s+=R((g=c.textContent)!=null?g:"")}return null}function E(e,t,l="smooth",n){var c,u,g;if(t<=0)return!1;if(n){let a=Array.from(e.querySelectorAll(x));for(let r of a)if(f((c=r.textContent)!=null?c:"").slice(0,m)===n)return r.scrollIntoView({behavior:l,block:"start"}),!0;for(let r of a)if(f((u=r.textContent)!=null?u:"").slice(0,m).slice(0,20)===n.slice(0,20)&&n.length>=20)return r.scrollIntoView({behavior:l,block:"start"}),!0}let i=document.createTreeWalker(e,NodeFilter.SHOW_TEXT,null),p=0,s;for(;s=i.nextNode();){let a=(g=s.textContent)!=null?g:"",r=R(a);if(r!==0){if(p+r>=t){let o=s.parentElement;for(;o&&o!==e;){let A=o.tagName.toLowerCase();if(d.includes(A))break;o=o.parentElement}if((!o||o===e)&&(o=s.parentElement),o)return o.scrollIntoView({behavior:l,block:"start"}),!0;break}p+=r}}return!1}function L(e){return T(e,0)}return H(w);})();\n';
