#!/usr/bin/env tsx
/**
 * Generates reading-progress-webview.generated.ts from reading-progress-webview-src.ts
 *
 * This script bundles the WebView-specific reading progress utilities into a
 * self-contained JavaScript string that can be injected into React Native WebViews.
 *
 * Usage:
 *   pnpm generate:webview-js         # Generate the file
 *   pnpm generate:webview-js --watch # Watch for changes and regenerate
 *   pnpm check:webview-js            # Check if file is up to date (for CI)
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";
import * as prettier from "prettier";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC_FILE = path.join(
  __dirname,
  "../utils/reading-progress-webview-src.ts",
);
const OUT_FILE = path.join(
  __dirname,
  "../utils/reading-progress-webview.generated.ts",
);

const isCheck = process.argv.includes("--check");
const isWatch = process.argv.includes("--watch");

async function build() {
  // Bundle the source file into an IIFE
  const result = await esbuild.build({
    entryPoints: [SRC_FILE],
    bundle: true,
    write: false,
    format: "iife",
    globalName: "__readingProgress",
    target: "es2015", // Broad compatibility for WebViews
    minify: true,
    platform: "browser",
  });

  const jsCode = result.outputFiles[0].text;

  // Generate the TypeScript wrapper
  const rawOutput = `// This file is auto-generated by scripts/build-webview-js.ts
// Do not edit manually. Run: pnpm --filter @karakeep/shared generate:webview-js
// Sources: reading-progress-webview-src.ts, reading-progress-core.ts

/**
 * WebView-compatible JavaScript for reading progress tracking.
 * Designed for React Native WebView injection.
 * Uses window-level scrolling only (no container scrolling detection).
 *
 * Exposes these functions on the __readingProgress global:
 * - normalizeText(text)
 * - normalizeTextLength(text)
 * - extractAnchorText(element)
 * - findParagraphByAnchor(container, anchor)
 * - getReadingPosition(container)
 * - scrollToReadingPosition(container, offset, behavior, anchor)
 */
export const READING_PROGRESS_WEBVIEW_JS = ${JSON.stringify(jsCode)};
`;

  // Format with prettier
  const prettierConfig = await prettier.resolveConfig(OUT_FILE);
  const output = await prettier.format(rawOutput, {
    ...prettierConfig,
    filepath: OUT_FILE,
  });

  if (isCheck) {
    // Check mode: compare with existing file
    const existing = fs.existsSync(OUT_FILE)
      ? fs.readFileSync(OUT_FILE, "utf-8")
      : "";
    if (existing !== output) {
      console.error(
        "ERROR: reading-progress-webview.generated.ts is out of date.",
      );
      console.error("Run: pnpm --filter @karakeep/shared generate:webview-js");
      process.exit(1);
    }
    console.log("reading-progress-webview.generated.ts is up to date.");
  } else {
    // Generate mode: write the file
    fs.writeFileSync(OUT_FILE, output);
    console.log(`Generated: ${OUT_FILE}`);
  }
}

async function watch() {
  console.log(`Watching ${SRC_FILE} for changes...`);

  // Initial build
  await build();

  // Watch for changes
  fs.watch(SRC_FILE, async (eventType) => {
    if (eventType === "change") {
      console.log("\nFile changed, rebuilding...");
      try {
        await build();
      } catch (err) {
        console.error("Build error:", err);
      }
    }
  });
}

if (isWatch) {
  watch().catch((err) => {
    console.error(err);
    process.exit(1);
  });
} else {
  build().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
